/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wavein_WaveInDev */

#ifndef _Included_com_wavein_WaveInDev
#define _Included_com_wavein_WaveInDev
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wavein_WaveInDev
 * Method:    rawNewWaveInDev
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wavein_WaveInDev_rawNewWaveInDev
  (JNIEnv *, jclass);

/*
 * Class:     com_wavein_WaveInDev
 * Method:    rawDeleteWaveInDev
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wavein_WaveInDev_rawDeleteWaveInDev
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wavein_WaveInDev
 * Method:    rawStartCapture
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_com_wavein_WaveInDev_rawStartCapture
  (JNIEnv *, jclass, jlong, jboolean, jboolean);

/*
 * Class:     com_wavein_WaveInDev
 * Method:    rawStopCapture
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_wavein_WaveInDev_rawStopCapture
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_wavein_WaveInDev
 * Method:    rawReadBytes
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_wavein_WaveInDev_rawReadBytes
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
